# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb1d161467c8c960eb2bb4ca36cba4309e2951da0ac3af2ee32032e0c7128f1aff383221732867d7f2dd29f494951f77fbfeba7c9b48a45a5c96c44b695f54c8

test:
  secret_key_base: 6adb5fc14a4f7d6f38f6ba7689f0bbe5029b9958e70babbd11a091fadf471b7ac712b06ebc7cfb9774d09067826b27f64d2318abf2a586b727f4d6bd466a2ddb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
